src/sample.cpp
test/sample_test.cpp

When a trace was started upstream and hit the new sampling code, it would get dropped - it was only making decisions about new traces and returning false for ones that weren't new.
This change makes it apply the configured rate when a trace was started upstream.
That means the trace wouldn't be submitted to the trace agent. However, it still gets "injected" downstream. Is that the right behaviour for existing traces, or should downstream tracing also be suppressed?
The alternative is #29, just letting the original sampling decision made upstream be definitive, capturing data and writing it, and also injecting downstream.

[bug] Existing traces were dropped. Apply sample rate for all traces.

---

src/span.cpp
src/span.h
src/span_buffer.cpp
src/span_buffer.h
src/tracer.cpp
src/tracer.h
src/writer.cpp
src/writer.h
test/integration/nginx/Dockerfile
test/integration/nginx/nginx_integration_test.sh
test/mocks.h
test/sample_test.cpp
test/span_buffer_test.cpp
test/span_test.cpp
test/tracer_test.cpp
test/writer_test.cpp

Moves span data (ids, names, tags, timing) to a simple struct class, separating it from the more complex OpenTracing Span implementation (that is now a wrapper for that struct).
This enforces a structural separation between data and OT-related behaviour. Specifically, this should in future prevent the kind of nasty bug I had before where a finished span awaiting writing kept invalid references to the tracer & buffer. 
It also means I could get rid of the template parameterisation for Buffer & Writer.
This fixes the nasty bug, of course :D 
Also changes the order of the fields in Span/SpanData to be more consistent.

Seperate Span data from OT Span behaviour

---

.circleci/config.yml
scripts/install_dependencies.sh
test/integration/nginx/Dockerfile
test/integration/nginx/dd-config.json
test/integration/nginx/expected.json
test/integration/nginx/index.html
test/integration/nginx/nginx.conf
test/integration/nginx/nginx_integration_test.sh

Building a shared plugin means no more distributing by deb package, since the plugin is more portable. This means we can simplify CI.
This also makes the integration test use the plugin, and makes it not flake in the case when more-than-1 agent requests are sent.

Simplify CI, build shared plugin

---

src/span.cpp
test/integration/nginx/expected.json
test/integration/nginx/nginx.conf
test/integration/nginx/nginx_integration_test.sh
test/span_test.cpp

This activates (in the integration test) the opentracing-nginx option to only create one span per request, which allows us to specify the span_name in the nginx config file.
It also adds a very basic (and cargo-culted from the Java tracer) regex that strips data from any tag named http.url, to help with PII and cardinality.

Improve URLs and Span Naming

---

.circleci/config.yml
test/integration/nginx/Dockerfile

Test image DL time 45s => 23s
Build image DL time 45s => 15s
I tried using Alpine, but got into issues with linking with their funky different libc and gave up for now (so ignore the branch name :D).

Use newer/smaller CI image

---

src/span.cpp
test/integration/nginx/expected.json
test/integration/nginx/nginx.conf
test/span_test.cpp

Allow resource-name-from-tag to take priority over operation-name-override. This allows us to have sanitised span names using operation_name_override, but still allow users to set their own resource names.

Set resource name independently of operation name in nginx tracing

---

.circleci/config.yml
README.md
examples/nginx-tracing/Dockerfile
examples/nginx-tracing/nginx.conf
scripts/install_dependencies.sh
src/tracer_factory.cpp
test/integration/nginx/Dockerfile

* Update nginx example. Moves from compiling the plugin from scratch to an actually useful example that shows how to use the release binaries.
* Update docs to reflect new example.
* Small fix to ensure libcurl is linked in statically.

Update nginx example and documentation

---

.circleci/config.yml

Removed during the CI cleanup, but I didn't realise that the default behaviour wasn't to build for tags.

Add back in the CircleCI config that builds artifacts for tags

---

src/propagation.cpp
test/integration/nginx/nginx_integration_test.sh
test/mocks.h
test/propagation_test.cpp
test/tracer_test.cpp

Does this PR look [familiar](https://github.com/DataDog/dd-opentracing-cpp/pull/40)? I've not been having good luck today with my git fat-fingering.
* Made the original commits.
* Made a new branch for another issue.
* Realised the mistake, reverted the commits in the new branch so it had just it's own fixes.
* Merged that branch.
* Merged from master into this branch, thus reverting the commits and leaving the PR empty!
* Derp.
So this is the exact same PR as 40, except as penance for my sins I added an integration test in addition to the unit test.
Original PR description:
First bug from a customer!
> one more nit, every request is generating an unnecessary error log:
> ```2018/08/09 23:08:23 [error] 95#95: *23 failed to extract an opentracing span context from request 00007FED59C66050: …
```

Fix issue where a lack of context was considered an error

---

src/tracer.cpp

rnburns kindly pointed out an issue with random number generation 
> btw it looks like your [method](https://github.com/DataDog/dd-opentracing-cpp/blob/master/src/tracer.cpp#L13-L17) of generating ids is going to run into this issue [#52](https://github.com/opentracing-contrib/nginx-opentracing/issues/52)
> 
> This is how I fixed it for the other tracers: [lightstep/lightstep-tracer-cpp#110](https://github.com/lightstep/lightstep-tracer-cpp/pull/110)

Ensure RNG seeded at fork

---

BUILD.bazel
src/writer.h
test/mocks.h

Trying to build from a basic ubuntu container with just-enough to compile envoy, and these missing headers were breaking that build.
They existed locally so no build errors occurred in the past.
(We can add CI for this when we upstream changes to envoy)

Removing includes that should have been purged

---

CMakeLists.txt
src/encoder.cpp
src/version_number.h.in
test/agent_writer_test.cpp

Thanks Alex :) 
It looks like "Datadog-Meta-Lang-Version : 201402"
In the future, maybe I can add compiler macros so we can see what's used.

Adds language version number and better checking for library version number

---

src/propagation.cpp
src/propagation.h
src/tracer.cpp
src/tracer.h
test/propagation_test.cpp

This adds support for "binary" context propagation.
To keep things simple, JSON is the format used for encoding the span details when using this propagation method.

Add support for propagation via C++ streams

---

scripts/release.sh

Without the quotes it was generating an array which is fine, but which doesn't work with read.

Fix support for multiple artifacts

---

BUILD.bazel
include/datadog/opentracing.h
src/encoder.cpp
src/encoder.h
src/propagation.cpp

Errors:
```
ERROR: missing input file '//:src/version_check.cpp'
ERROR: /home/ubuntu/datadog/dd-opentracing-cpp/BUILD.bazel:1:1: //:dd_opentracing_cpp: missing input file '//:src/version_check.cpp'
```
and
```
bazel-out/k8-fastbuild/bin/external/com_github_datadog_dd_opentracing_cpp/_virtual_includes/dd_opentracing_cpp/datadog/opentracing.h:53:47: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
virtual const std::size_t pendingTraces() = 0;
```
Warnings:
```
src/propagation.h:86:48: warning: 'datadog::opentracing::SpanContext::baggage_' will be initialized after [-Wreorder]
std::unordered_map<std::string, std::string> baggage_;
^
src/propagation.h:81:48: warning:   'bool datadog::opentracing::SpanContext::nginx_opentracing_compatibility_hack_' …
```

Fixes errors and warnings when building with bazel

---

CMakeLists.txt
scripts/install_dependencies.sh
src/span.cpp

Two definitions of static!
* Firstly, link libz so it can be used by curl
* Secondly, avoid static initialization of regex (which seems to sometimes fail when library loaded via dlopen)

Better static behaviour

---

.circleci/config.yml
BUILD.bazel
CMakeLists.txt
src/noopspan.cpp
src/propagation.cpp
src/sample.cpp
src/span.cpp
src/span_buffer.cpp
src/span_buffer.h
src/tracer.h
src/transport.cpp
test/mocks.h
test/sample_test.cpp
test/span_test.cpp
test/tracer_factory_test.cpp
test/tracer_test.cpp

Following from the datadog-library PR that adds bazel to the "build" image, this PR uses that image and runs `bazel build` on the project.
Part of this change is adding a strict set of compiler error and warning flags to match downstream projects (eg: envoy), and this PR includes fixes for the errors that were emitted.
Since the cmake build compiles a different set of files, those flags could also be added to the cmake config as a separate change.

Add a CI job that builds dd-opentracing-cpp using bazel

---

src/propagation.h

This caused an error when running some (not all) of the tests in envoy's CI for our submission.

Fix mismatched tag from refactoring.

---

.circleci/config.yml

Related to #61, the error was not detected in regular build / test cycles because GCC compilers were used for those.
Some jobs deep within a different project use clang compilers for tsan / asan test runs, and would fail with a compilation error.
This makes sure we catch them.
Note: red build, will need rebasing after merging #61 and Datadog/docker-library#17, and pushing a new build image.

Use clang-5.0 for bazel compile stage

---

.circleci/config.yml
README.md
examples/nginx-tracing/Dockerfile
test/integration/nginx/Dockerfile

There's no real reason not to use RelWithDebInfo, if someone needs a very slightly smaller binary we can create a second build, but I think it's unlikely for now.
Also, CI changes. For the OpenTracing 1.5 upgrade, we had to switch to building Nginx-OT ourselves to break a circular dependency. I'm adding that back in, now that the upgrade is done, so that we can continue to test against the real releases of Nginx-OT, more accurately testing what our customers will be using.
Also updated some docs.

Debug symbols in Release

---

README.md
include/datadog/opentracing.h
src/propagation.cpp
src/propagation.h
src/span_buffer.cpp
src/tracer_factory.cpp
test/integration/nginx/dd-config.json
test/propagation_test.cpp
test/sample_test.cpp
test/span_test.cpp

When writing up the RFC for Sampling Priority, I noticed a few cases where we weren't in-line with the spec. This fixes them:
- Priority sampling should be on by default (spec change)
- When receiving a propagated trace without an existing sampling priority, assign one
- Don't set metrics field unless it's the root span

Sampling improvements

---

include/datadog/opentracing.h
src/encoder.cpp
src/encoder.h

This PR is related to feedback on the envoy tracer and doing things in ways that improve performance.
Adds references, uses static consts for string keys.

Return references and use static strings

---

src/noopspan.cpp
src/noopspan.h
src/tracer.cpp

This makes the tracer implementation set tags when `StartSpanWithOptions` is called.
A special case is required for the `opentracing::ext::sampling_priority` tag, because it may have been assigned already from the propagated context, and can't be changed after that assignment.
This fixes an issue with envoy, which traces all requests.
It has config options to trace a specific percentage of requests, and when it decides not to sample a trace, it passes the `opentracing::ext::sampling_priority` tag in, with the value `0`.
This change makes sure that tag is respected and applied to the span.

Apply options.tags when creating spans.

---

CMakeLists.txt

This PR contains several improvements for `CMakeLists.txt` file:
* `SOVERSION` property which creates `.so.0` files, not only `.so`.
* Usage of GNUInstallDirs for libdir and includedir, which allows to override the destination where include files and libraries are installed.
The main motivation is my plan to create the RPM package for dd-opentracing-ccp in openSUSE, which requires `.so.*` files and ability to use `/usr/lib64` directory.

Several improvements in cmake configuration

---

src/span.cpp
test/span_test.cpp

When a span is finalized, the operation_name_override would replace the values of both `name` and `resource` with the override value.
It renders better in the trace list and flame chart if only the name is replaced with the override value, instead of showing the same value in both name and resource parts of the span.

Make operation_name_override only apply to span name

---

include/datadog/tags.h
src/span.cpp
src/span.h
src/tracer.cpp
test/span_test.cpp

This refactors all the existing datadog-specific tags into a public header, in addition to adding special behavior for the analytics_event tag.
Note: support for `DD_ANALYTICS_ENABLED` and `DD_<INTEGRATION>_ANALYTICS_ENABLED` environment variables is not included because there are no integrations to enable it for. All cases will effectively be custom integrations and unaffected by those environment variables.

Add support for trace analytics

---

src/tracer.cpp

gcc 9 reports this move as redundant:
```
[yuval@localhost envoy]$ gcc --version
gcc (GCC) 9.0.1 20190312 (Red Hat 9.0.1-0.10)
```
Gives this:
```
external/com_github_datadog_dd_opentracing_cpp/src/tracer.cpp: In member function 'virtual std::unique_ptr<opentracing::v2::Span> datadog::opentracing::Tracer::StartSpanWithOptions(opentra
cing::v2::string_view, const opentracing::v2::StartSpanOptions&) const':
external/com_github_datadog_dd_opentracing_cpp/src/tracer.cpp:101:19: error: redundant move in return statement [-Werror=redundant-move]
101 |   return std::move(span);
|          ~~~~~~~~~^~~~~~
```

remove redundant move

---

src/span.cpp
src/span.h
src/span_buffer.cpp
src/span_buffer.h
src/tracer.cpp
src/tracer.h
test/mocks.h
test/propagation_test.cpp
test/sample_test.cpp
test/span_buffer_test.cpp
test/span_test.cpp
test/tracer_test.cpp

When `DD_TRACE_REPORT_HOSTNAME` is set to `true`, an additional tag is added to traces automatically, containing the hostname.

Add DD_TRACE_REPORT_HOSTNAME functionality

---

test/integration/nginx/Dockerfile

A tool (msgpack-cli) used in integration tests stopped compiling because a dependency refactored some things. This change pins the dependency to an older version.
A proper solution can be worked on once integration tests are working again.

Quick workaround for failing integration test

---

BUILD.bazel

Envoy uses this library via a bazel dependency.
Bazel needs to have all files listed in specific categories.
The new `tags.h` header wasn't added to the bazel spec, so it needs this change before it can be compiled with envoy.
The `WORKSPACE` may also be unnecessary for the "bazel dependency" use case, but it seems to be harmless for now, so it can wait for a future PR.

Add new header to BUILD.bazel

---

3rd_party/include/catch2/catch.hpp
src/span.cpp
src/span.h
src/span_buffer.cpp
src/span_buffer.h
src/tracer.cpp
src/tracer.h
test/mocks.h
test/span_test.cpp
test/tracer_test.cpp

This PR makes it possible to set the trace analytics metric on traces via an environment variable.
Users of this tracer are generally not directly writing C++ code, but using it indirectly via another application (eg: nginx, envoy, istio).
Under those circumstances, the most practical way of controlling a feature like this is via environment variables.
The variables used are:
- `DD_TRACE_ANALYTICS_ENABLED`: can be `true` (rate=1.0), `false`(rate=0.0) or unset (no rate)
- `DD_GLOBAL_ANALYTICS_SAMPLE_RATE`: a valid value between 0.0 and 1.0 inclusive.

Add support for setting trace analytics via environment variables.

---

src/span.cpp
test/span_test.cpp

Envoy adds a tag `guid:x-request-id` to the trace spans. However, this value can't be used as a facet in trace analytics.
This PR replaces the `:` with `.` in tag names, which is acceptable for making a facet.

Replace ':' in span tag keys with '.'

---

test/CMakeLists.txt
test/agent_writer_test.cpp
test/opentracing_test.cpp
test/propagation_test.cpp
test/sample_test.cpp
test/span_buffer_test.cpp
test/span_test.cpp
test/test_main.cpp
test/tracer_factory_test.cpp
test/tracer_options_test.cpp
test/tracer_test.cpp

This PR doesn't actually enhance the library performance, but compile time when building with `BUILD_TESTING=ON` is faster by around 50%.
I've measured compilation time with `time (cmake -DBUILD_TESTING=ON .. && make && ctest --output-on-failure)`.
Before:
`128,05s user 5,15s system 98% cpu 2:14,64 total`
After:
`72,01s user 3,73s system 98% cpu 1:17,00 total`
As recommended by Catch2 documentation on this [README](https://github.com/catchorg/Catch2/blob/master/docs/slow-compiles.md) it's better to build Catch2 `main` in a separate static library and link each test to it, this way Catch2 `main` is generated and built only once and changing a test doesn't require rebuilding it.

Changed how tests are built for faster compilation

---

.circleci/config.yml
include/datadog/version.h
test/version/current_version.cc
test/version/version_check

The release of v1.1.0 would report traces with the incorrect, earlier version (v1.0.1).
This PR updates the version and makes sure the CI rejects PRs when the version has become outdated, eg: HEAD is newer than the version inside the header.

version bump for 1.1.1 and version check scripts enforced by CI

---

include/datadog/version.h
src/tracer.cpp

Some other tracer implementations don't yet support IDs larger than 2^63.
This makes sure the generated IDs are kept within the supported limits.
Also version bump.

Generate int64 values instead of uint64

---

examples/nginx-tracing/Dockerfile
examples/nginx-tracing/docker-compose.yml
include/datadog/version.h

Small fixes to the nginx sandbox
- opentracing-nginx stopped providing builds for nginx 1.14.0, updated to 1.14.2
- removed port binding for `127.0.0.1:8126`: it's not needed

Fix nginx example / sandbox

---

include/datadog/opentracing.h
src/encoder.cpp
src/encoder.h
test/sample_test.cpp

This is part of a fix for envoyproxy/envoy#9076, so that tracers have a chance to be involved in sampling decisions. In a distributed trace, it's not great if middle-bits make their own sampling decisions.
So this exposes a method for envoy to call, and report back a tracer-based decision.

Expose sampling decision to external tracers

---

CMakeLists.txt

Not sure if this is necessary, but it's a nicer default to be using.

Default to RelWithDebInfo for cmake

---

src/tracer.cpp
test/sample_test.cpp

This came up as part of #117, and since there's some use of rate sampling, this is to make it "play nicely" with priority sampling.
Essentially: rate sampling is not applied to a distributed trace that already has a sampling decision.

Rate sampler not overriding distributed sampling decision

---

include/datadog/opentracing.h
src/tracer.cpp
src/tracer_factory.cpp
src/tracer_options.cpp
test/tracer_factory_test.cpp
test/tracer_options_test.cpp
test/tracer_test.cpp

This was requested in #110 in relation to `ingress-nginx`.
Some options in the tracer were only configurable via environment variables.
This doesn't work well for nginx because it ignores most environment variables when launching unless explicitly configured to keep them.
In that circumstance, it's easier to expose them via the tracer's JSON config.
Fixes #110

Exposes additional tracer options in config struct and JSON

---

include/datadog/opentracing.h
src/encoder.cpp
src/encoder.h
test/sample_test.cpp

Reverts DataDog/dd-opentracing-cpp#121
This didn't have the intended effect, so it needs reverting before shipping the next release.

Revert "Expose sampling decision to external tracers"

---

examples/cpp-tracing/compiled-in/Dockerfile
examples/cpp-tracing/compiled-in/docker-compose.yml

Because of other changes, this wouldn't build without the additional compiler flags.
Removed port binding from docker-compose as well. It's not needed, and can conflict with other things happening on the host.

Fix build and launch issues for the compiled-in example

---

include/datadog/opentracing.h
src/agent_writer.cpp
src/agent_writer.h
src/opentracing_agent.cpp
src/tracer_factory.cpp
src/tracer_options.cpp
test/agent_writer_test.cpp
test/tracer_factory_test.cpp

Fixes #125 
Lets users provide a path to the trace-agent socket in addition to the agent's host/port.
This PR doesn't include an integration test (yet) but it has been tested locally.
The agent needs to have the `DD_APM_RECEIVER_SOCKET` environment variable set, and the C++ application needs to have the same path configured in JSON or using the `DD_TRACE_AGENT_SOCKET` environment variable.
In containerized setups (eg: kubernetes), the directory containing the socket should be mounted by both agent container and the application submitting traces.

Add support for traces sent using UNIX domain sockets

---

.gitignore
include/datadog/version.h
src/limiter.cpp
test/CMakeLists.txt

Under some environments, `std::chrono::duration` uses `long` for representing the value, and others use `long long`. In the latter, it caused an error comparing against a `long` using `std::min`.
It could have been fixed using `std::common_type`, but a simpler fix with a basic if comparison was chosen instead.
When running tests on macos, one specific test would fail in a mysterious way, when comparing against an essentially static value. This was somehow due to the orders libraries were linked causing trouble on this environment. (It didn't occur with Linux/GCC).

Small fixes for macos / clang builds

---

examples/envoy-tracing/check_envoy_configs.sh
examples/envoy-tracing/docker-compose.yml
examples/envoy-tracing/envoy-ed6a1b8.yaml
examples/envoy-tracing/envoy-v1.11.yaml
examples/envoy-tracing/envoy-v1.12.yaml
examples/envoy-tracing/envoy-v1.13.yaml
examples/envoy-tracing/envoy-v1.14.yaml

Adding static runnable examples for envoy across recent major versions.
There's small differences between each version when configuring tracing, and sometimes these tiny details make the difference between making things work successfully and not working at all.
I need to put these somewhere so a reference to "older versions" can be added to the main documentation.

Add example configs for major envoy versions

---

examples/nginx-tracing/Dockerfile
examples/nginx-tracing/docker-compose.yml
examples/nginx-tracing/nginx.conf

Changing the dockerfile to use an `nginx` base image instead of `ubuntu` and then installing nginx. The `nginx` base image has extra rules that make access/error logs go to the container's `stdout`/`stderr`.
Also modified the `log_format` in `nginx.conf` to verify that logs and traces can be connected.
Note: it doesn't work OOTB with the existing NGINX logs integration, but can be made to work by duplicating it and updating the grok parser and adding a Trace ID Remapper.

Update nginx example, make dockerfile useful as reference

---

src/tracer.cpp
src/tracer.h
test/tracer_test.cpp

This can be disabled by setting the environment variable `DD_TRACE_STARTUP_LOGS=0`.
The purpose of these logs is to assist with troubleshooting, so there's a simple and definitive source of the settings that affect traces being captured and sent to the agent.
The log files are created in `/var/tmp/dd-opentracing-cpp`. An example filename is `/var/tmp/dd-opentracing-cpp/startup_options-1594274838900439942.json` with the contents:
```json
{"agent_url":"http://localhost:8126","analytics_enabled":false,"analytics_sample_rate":null,"date":"2020-07-09T06:07:18+0000","enabled":true,"env":"","lang":"cpp","lang_version":"201402","report_hostname":false,"sampling_rules":"[{\"sample_rate\": 1.0}]","service":"compiled-in example","version":"v1.2.0"}

Write tracer options to a log file at startup

---

src/span.cpp
src/span.h
src/tracer.cpp
src/tracer.h
test/integration/nginx/Dockerfile
test/integration/nginx/expected_tc6.json
test/span_test.cpp

The `http.url` tag gets obfuscated too heavily, to the point where it's not very useful. It was also inconsistent with other tracers.
This PR makes it consistent with other tracers, but has an option to keep using the "legacy obfuscation" by setting an environment variable: `DD_TRACE_CPP_LEGACY_OBFUSCATION=1`
Fine-grained control of replacements can be configured on the agent using [tag filtering](https://docs.datadoghq.com/security/tracing/#tag-filtering)

Change URL obfuscation behavior

---

BUILD.bazel
include/datadog/version.h
src/bool.cpp
src/bool.h
src/span.cpp
src/span_buffer.cpp
src/span_buffer.h
src/tracer.cpp
src/tracer_options.cpp
src/tracer_options.h
test/mocks.h
test/tracer_test.cpp

Adds DD_TRACE_ENABLED that can be set to false. When set to false, the traces will still be generated and propagated as usual, but not sent to the agent.
Add bool parsing functions to clean up places that relied heavily on comparing strings to `true`, `false`, `1`, `0` etc.
Fix parsing of DD_PROPAGATION_STYLE variables, so that it allows comma-separated values instead of only space-separated.
Add bool parsing functions to clean up places that relied heavily on comparing strings to `true`, `false`, `1`, `0` etc.
Some opportunities to refactor code or add new tests were ignored for now to keep this fairly minimal.

Improve environment variable consistency between C++ tracer and other datadog tracers

---

src/bool.cpp

Some versions of clang report an error `error: implicit instantiation of
undefined template` (macos and envoy ci).
I haven't figured out the exact compiler and options though - no error
using clang from LLVM repos. That mystery can be figured out later.

Fix error building with clang compilers

---

CMakeLists.txt
README.md
examples/cpp-tracing/compiled-in/tracer_example.cpp
include/datadog/opentracing.h
src/sample.h
src/tracer.cpp
src/transport.cpp
src/transport.h
test/mocks.h
vcpkg.json

This adds support for building the C++ tracer on Windows using Visual Studio 2019.
Older versions may work but have not been tested.
It has been tested by manually building and running the tracer_example and confirming traces are reported and appear in the UI.
More work will be required to cover building and running the tracer's suite of tests, CI integration and other details related to the Windows ecosystem.
Fixes #134

Initial support for Windows / MSVC

---

examples/nginx-tracing/docker-compose.yml

The second setting of environment for traced-nginx was overriding the first, which can be confusing when testing things and makes no sense to have.

Remove second setting of environment variables for traced-nginx

---

examples/nginx-tracing/Dockerfile
include/datadog/version.h
test/integration/nginx/Dockerfile

As reported in #168. the examples should be using the "ot16" build of nginx modules.

Update examples to use nginx-opentracing's ot16 module

---

.circleci/config.yml

The self-hosted base image was needed briefly to pass CI checks for nginx-opentracing after it had changed to use opentracing 1.6.0 but before shipping a new release. It has been released now and updated nginx-opentracing images are available.
This PR changes the nginx integration test to use a newer image.
Mildly urgent as this blocks other PRs from having all CI checks passing. It was noticed on #175

Use nginx-opentracing base image for integration test

---

test/integration/nginx/Dockerfile

When I ran `run_integration_tests_local.sh`, it would fail with an HTTP 404 for the release artifact whose name is constructed [here][1].  I looked around for a similarly named release, and then updated the variables in the `Dockerfile`.  I don't know what consequences this might have, but "it works now."  I also verified that `sudo /usr/local/bin/circleci local execute --job=integration_test_nginx` succeeds (the `sudo` needed on my system is I think an artifact of my use of rootless docker and circleci's use of `/var/run/docker.sock`).
Let's see if the CI comes up with anything fishy, and let me know if changing these versions is unkosher.
[1]: https://github.com/DataDog/dd-opentracing-cpp/blob/68dba8d27d5773a6603b7f2fbfef0cd877907930/test/integration/nginx/Dockerfile#L30

update versions of dependencies in integration test

---

examples/nginx-tracing/nginx.conf

Something I should have noticed while merging other PRs. Thanks @rmangi for pointing it out

Fix duplicate env entries in example nginx config

---

src/tracer_factory.cpp
test/agent_writer_test.cpp
test/tracer_factory_test.cpp

Catch exceptions thrown in the constructor of `AgentWriter` to avoid crashes when dynamically loading the library with unsupported URLs.
In some cases, the `AgentWriter` throws in the constructor (unsupported URL schemes and failed calls into CURL). Those exceptions aren't caught in the `MakeTracer` function which is marked as `noexcept` and therefore the application is terminated.
Note: Other invalid URLs are happily accepted by the tracer and result in just logged errors when CURL tries to ingest the traces.
Background: I noticed that in nginx-ingress controller. Result of configuring an unsupported URL scheme before the change:
```
ingress-nginx-controller-7456599f48-r6lbk controller Error: signal: aborted (core dumped)
ingress-nginx-controller-7456599f48-r6lbk controller terminate …
```

Catch runtime errors when creating `AgentWriter`.

---

.circleci/config.yml
src/version.cpp

The version needed bumping due to the release that shipped recently.
Also the nginx-opentracing image was reporting an error when performing `apt-get update`. Updated to a newer nginx-opentracing image.

Fixes to make CI happy

---

include/datadog/opentracing.h

(Should) fix https://github.com/DataDog/dd-opentracing-cpp/issues/195.
I did not test it yet this version where we had the issues but it would be nice to check that before merging it, unless reviewers of this are already confident it will do the trick to fix the issue mentioned above.
Concatenation with "+" may not be the most performant thing but anyway this default logging function is very rarely used. I only saw the log in #195 using this format.
Also, are we ok that the log message will still be flushed to `stderr` correctly, even if it's not using `std::endl`?
Finally, I'm not sure to understand why the "build" step of CI is failing, but it also fails on other recent PR :thinking:

Fix mixed log using string concat

---

src/propagation.cpp
test/propagation_test.cpp

In internal support ticket APMS-6017, a customer has an old (Java) tracer that's producing `trace_id`s that are hexadecimal strings.
When the C++ tracer is parsing a `trace_id` from a header, it accepts any string that begins with decimal digits (possibly with leading whitespace), i.e. any string matching `\s*[+]?(0|[1-9][0-9]+)([^0-9].*)?`. This is due to the use of [std::stoull][1].
In this pull request, I modify the parsing code to further require that the parsed decimal integer is followed by whitespace only.  This way, decimal prefixes of hexadecimal `trace_id`s will fail to parse, rather than successfully parsing the decimal prefix.
These changes might break things.  Let's discuss if/how to roll this out.
[1]: https://en.cppreference.com/w/cpp/string/byte/strtoul

disallow trailing letters when parsing decimal integer

---

.circleci/config.yml
CMakeLists.txt
scripts/install_dependencies.sh
scripts/run_unit_tests.sh
src/agent_writer.cpp
src/agent_writer.h
src/tracer_factory.cpp
src/tracer_factory.h
test/agent_writer_test.cpp
test/tracer_factory_test.cpp

This adds a job to CircleCI, `test_coverage`, that builds the library and its unit tests with coverage enabled, and then runs the tests, generates a coverage report website using `lcov`, and saves the tar'd gzip'd result as a build artifact.
This PR depends on changes to the build image in https://github.com/DataDog/docker-library/pull/74. I needed to add `lcov` and upgrade the version of `cmake` by using a more recent Ubuntu distribution. Before we can merge this PR, we must merge https://github.com/DataDog/docker-library/pull/74 and publish the new Docker image.
Update: The sanitized test jobs didn't like the newer version of Ubuntu. This pull request now includes various workarounds to:
- allow multiple concurrent `make` jobs
- prevent "\<nil\>" from appearing on `env` commands
- avoid …

add CI job to generate code coverage report

---

.circleci/config.yml
src/agent_writer.cpp
src/agent_writer.h
src/encoder.cpp
src/encoder.h
src/logger.cpp
src/logger.h
src/opentracing_agent.cpp
src/opentracing_external.cpp
src/propagation.cpp
src/span_buffer.cpp
src/tracer.cpp
src/tracer.h
src/tracer_factory.h
src/transport.cpp
src/transport.h
src/writer.cpp
src/writer.h
test/agent_writer_test.cpp
test/mocks.h
test/sample_test.cpp
test/tracer_test.cpp

As part of my work on the new nginx module, I'm plugging this library's logging into nginx's logging system. I noticed that some of our library prints directly to standard error rather than using a `Logger` object. This revision makes a `Logger` object available to more components in the library.

use the Logger class wherever possible

---

examples/cpp-tracing/compiled-in/docker-compose.yml
examples/cpp-tracing/dynamic-loading/docker-compose.yml
examples/cpp-tracing/dynamic-loading/tracer_example.cpp

When building the current compiled in example, it will lead to this error about traces being refused:
```
Error sending traces to agent: Couldn't connect to server
Failed to connect to localhost port 8126: Connection refused
```
I am making this change to correct this so traces can be sent to the Datadog Agent container (defined as `dd-agent` in the `docker-compose.yml`).
I have updated both the dynamic loading and compiled-in examples so that they both use `localhost` in the code but **DD_AGENT_HOST** in the Docker Compose file.
With this update, this is the expected output of the start up logs:
Compiled-In Example:
```
info: DATADOG TRACER CONFIGURATION - {"agent_url":"http://dd-agent:8126","analytics_enabled":false,"analytics_sample_rate":null,"date":"2021-12-14T20:28:53+0000","enabled" …
```

Update container connections for compiled in and dynamic loading examples

---

.github/workflows/codeql-analysis.yml

Static code analysis on dd-opentracing-cpp using Github's Code Scanning.
This PR has Github workflow configs to trigger the Code Scanning on every PR and on push to master branch. As of now only default security based CodeQL queries are configured. We can gradually add queries for Code Quality later. It is a part of Datadog compliance requirements to regularly perform code-scanning on all the customer installed code.
Code Scanning results for this branch: https://github.com/DataDog/dd-opentracing-cpp/security/code-scanning?query=pr%3A219+

[CSEC-334] Setup Code Scanning on dd-opentracing-cpp

---

include/datadog/opentracing.h
src/limiter.cpp
src/limiter.h
src/opentracing_agent.cpp
src/opentracing_external.cpp
src/sample.cpp
src/sample.h
src/tracer.cpp
src/tracer_factory.cpp
src/tracer_factory.h
src/tracer_options.cpp
src/tracer_options.h
test/integration/nginx/Dockerfile
test/integration/nginx/expected_tc1.json
test/integration/nginx/nginx_integration_test.sh
test/limiter_test.cpp
test/sample_test.cpp
test/tracer_options_test.cpp
test/tracer_test.cpp

_Tip: Tell github to "hide whitespace" for this diff.  I moved some `try` blocks around, which changed indentation._
These revisions address the issue raised in customer issue APMS-6277 ("Attempting to use configuration 'max_traces_per_second' to limit tracing to 5 per second") and the work item OKR2,KR1 ("`DD_TRACE_SAMPLE_RATE` implemented and documented").
Brett mentioned that in `dd-trace-py`, the `DD_TRACE_SAMPLE_RATE` environment variable results in the equivalent sampling rule being appended to any other rules that the user might have specified. This means that agent-led priority sampling only happens if `DD_TRACE_SAMPLE_RATE` doesn't have a value.  Additionally, the rule-based sampler's limiter can be configured using the environment variable `DD_TRACE_RATE_LIMIT`.
All of that …

make the rules sample limiter and default sampling rate configurable

---

CMakeLists.txt
include/datadog/opentracing.h
scripts/install_dependencies.sh
src/tracer.cpp
src/tracer.h
src/tracer_factory.cpp
src/tracer_options.cpp
test/integration/nginx/Dockerfile
vcpkg.json

This is an identical replacement for https://github.com/DataDog/dd-opentracing-cpp/pull/221
Signatures got removed from my commits, I think by Github's in-browser merge conflict resolution tool.
I tried to rebase to add signatures to the commits, but I was getting conflicts at every step, for some reason.
Instead, this is `git diff master` relative to `david.goffredo/changes-for-nginx-module`, applied onto a new branch based off of `master` (`david.goffredo/changes-for-nginx-module-redux`).
Lesson learned.

Apply changes from #221 as one signed patch.

---

scripts/release.sh
src/version.cpp

While working on producing a release, I noticed these improvements that could be made to the release script.
First thing to stick out was the idea that "you should use `go install`" is a thing.
Then I added some calls to `command -v` to better track command line tool dependencies of the script.
This revision also updates the library version in `version.cpp` to `v1.3.3`, since I just produced release `v1.3.2`.

"go install" and other changes

---

src/span.cpp
src/span.h

I'm writing some unit tests involving `SpanData` and I think that restricting access to its constructors is unnecessary.

SpanData is just data

---

doc/configuration.md
doc/sampling.md
include/datadog/opentracing.h

Span sampling rules are implemented, but the necessary changes to the Datadog Agent have yet to be released.
I want to produce a release of this library for the sake of `X-Datadog-Tags`.  Rather than base the release off of an older revision, I'll add this disclaimer to the documentation of the span sampling rules.

add a disclaimer to the documentation, in preparation for a release

---

.circleci/config.yml
src/version.cpp

The new image is based off of an older Ubuntu (18 instead of 20),
and rather than use the distribution's version of cmake, the image's
Dockerfile downloads a recent binary release of cmake instead.
I tested this locally, but haven't run the integration tests.  Let's see how CircleCI copes.

Tell CircleCI to build in the newly pushed 0.3.8 image.

---

src/span_buffer.cpp
src/span_buffer.h
src/span_context.cpp
test/integration/nginx/nginx_integration_test.sh
test/propagation_test.cpp

nginx-opentracing constrains us to set non-empty values for all propagation headers we wish to register in the "hack," or else a (harmless) error message will be printed to the nginx error log.
Propagating an empty header is silly, but will do no harm.  Nginx will not send it anyway, and Envoy is unlikely to be affected by these changes as we move to a new library there.

Always serialize X-Datadog-Tags

---

src/bool.cpp
src/bool.h
src/span.cpp
test/span_test.cpp

This revision makes spans aware of the `error.msg`, `error.stack`, and `error.type` tags.
These changes grew out of Andrew Glaude's investigation of compatibility between the C++ tracer and "error tracking": https://docs.datadoghq.com/tracing/error_tracking/.
The new behavior is best summarized by the table of test cases in the added `SECTION` of [test/span_test.cpp](https://github.com/DataDog/dd-opentracing-cpp/compare/david.goffredo/error-tags?expand=1#diff-2bcf8accc397819e5fd6c3bb04a96fbbd9d63479238b27861f4bfb1b2234f2a5).
@ajgajg1134 (he's on vacation) FYI.
Also, when these changes are finalized, we'll want to update these docs: https://docs.datadoghq.com/tracing/trace_collection/custom_instrumentation/cpp/#set-errors-on-a-span

error tags

---

doc/sampling.md
include/datadog/opentracing.h

The next release of the Datadog Agent, 7.40, will contain the code necessary for span sampling rules to have their intended effect.
This PR updates our documentation accordingly.

mention the Agent version required for span sampling

---

src/version.cpp

bump version number to future version

---

src/tracer_options.cpp
test/tracer_options_test.cpp

Colons are allowed in Datadog tags. This adds a test case ensuring support.
https://docs.datadoghq.com/getting_started/tagging/#define-tags

Add DD_TAGS colon edge case test

---

examples/cpp-tracing/compiled-in/Dockerfile
examples/cpp-tracing/compiled-in/build_and_run_example.sh
examples/cpp-tracing/compiled-in/docker-compose.yml
examples/cpp-tracing/dynamic-loading/Dockerfile
examples/cpp-tracing/dynamic-loading/build_and_run_example.sh
examples/cpp-tracing/dynamic-loading/docker-compose.yml
examples/cpp-tracing/unix-domain-socket/Dockerfile
examples/cpp-tracing/unix-domain-socket/bin/install-latest-dd-opentracing-cpp
examples/cpp-tracing/unix-domain-socket/bin/run
examples/cpp-tracing/unix-domain-socket/docker-compose.yaml
examples/nginx-tracing/docker-compose.yml

The CMake version required to build dd-opentracing-cpp was increased recently, but the examples/ were not updated to use a version of Ubuntu that had the required version.
This commit updates the Docker base images used in the examples, as well as tweaks the examples to build faster and a couple of other conveniences.

Fix examples to work with most recent release.

---

scripts/format.sh
src/agent_writer.cpp
src/transport.cpp
src/transport.h
test/agent_writer_test.cpp
test/mocks.h

Currently, the `AgentWriter` passes all response bodies to the `AgentHttpEncoder`. The `AgentHttpEncoder` then interprets the body as a JSON object. However, when the HTTP response status does not indicate success, the agent does not return a JSON response body.
This revision logs an error whenever a non-success HTTP response status is delivered by the agent.

log an error when the agent responds with a non-success HTTP status

---

src/version.cpp

This is to unblock the CI check affecting #262

bump version::tracer_version to future version v1.3.8

---

examples/envoy-tracing/check_envoy_configs.sh

Removing a legacy `/apm/livetail` link.

Remove legacy /apm/livetail link

---

examples/cpp-tracing/compiled-in/Dockerfile
examples/cpp-tracing/dynamic-loading/Dockerfile
examples/cpp-tracing/dynamic-loading/docker-compose.yml
examples/cpp-tracing/unix-domain-socket/Dockerfile
examples/cpp-tracing/unix-domain-socket/bin/install-latest-dd-opentracing-cpp
examples/nginx-tracing/Dockerfile

As part of an audit, a couple of relatively benign changes were suggested.
```
semgrep --config "p/owasp-top-ten" --config "p/cwe-top-25" --config "p/r2c-security-audit" --text
```
For simplicity, a couple of additional changes were made
- install specific version of dd-opentracing-cpp and opentracing-cpp instead of using get_latest_release
- remove port binding from docker-compose

Fix findings from running semgrep
